<?php

namespace App\Services\Recharge;

use App\Services\Portal\PortalSettings;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class RoundpayService
{
    protected PortalSettings $settings;

    public function __construct(PortalSettings $settings)
    {
        $this->settings = $settings;
    }

    /**
     * Execute recharge via Roundpay API
     *
     * @param string $apiRequestID Unique request ID generated by aggregator
     * @param string $account Mobile or DTH number
     * @param float $amount Recharge amount
     * @param string $spKey Operator Specific Service Provider key
     * @param string|null $geocode Optional client geo location (fallback to default)
     * @param string|null $customerNumber Optional client customer number (fallback to default)
     * @param string|null $pincode Optional client area pincode (fallback to default)
     * @return array{status: string, msg: string, bal?: float, errorCode?: string, rpid?: string, opid?: string}
     */
    public function executeRecharge(
        string $apiRequestID,
        string $account,
        float $amount,
        string $spKey,
        ?string $geocode = null,
        ?string $customerNumber = null,
        ?string $pincode = null
    ): array {
        $apiUrl = $this->settings->roundpayApiUrl();
        $params = [
            'UserID' => $this->settings->roundpayUserId(),
            'Token' => $this->settings->roundpayToken(),
            'Account' => $account,
            'Amount' => $amount,
            'SPKey' => $spKey,
            'APIRequestID' => $apiRequestID,
            'GEOCode' => $geocode ?: ($this->settings->roundpayDefaultGeocode() ?: '80.94,26.85'),
            'CustomerNumber' => $customerNumber ?: ($this->settings->roundpayDefaultCustomer() ?: '9999999999'),
            'Pincode' => $pincode ?: ($this->settings->roundpayDefaultPincode() ?: '226001'),
            'Format' => $this->settings->roundpayFormat() ?: '1',
            'isReal' => $this->settings->roundpayIsReal() ?: '1',
            'routeType' => $this->settings->roundpayRouteType() ?: '3',
        ];

        try {
            Log::info('Roundpay Recharge Request: URL ' . $apiUrl, ['params' => array_merge($params, ['Token' => '***'])]);

            $response = Http::timeout(30)->get($apiUrl, $params);

            if ($response->failed()) {
                Log::error('Roundpay API request failed', [
                    'status' => $response->status(),
                    'body' => $response->body()
                ]);

                return [
                    'status' => 'failed',
                    'msg' => 'Provider Connection Failure',
                    'errorCode' => 'HTTP_' . $response->status(),
                ];
            }

            $data = $response->json();
            Log::info('Roundpay Recharge Response', ['body' => $data]);

            if (empty($data)) {
                return [
                    'status' => 'failed',
                    'msg' => 'Empty Response from Provider',
                    'errorCode' => 'EMPTY_RESPONSE',
                ];
            }

            // Roundpay Status values:
            // "2" = SUCCESS
            // "1" = PENDING
            // "3" = FAILED
            $statusVal = (string) ($data['STATUS'] ?? '');

            if ($statusVal === '2') {
                return [
                    'status' => 'success',
                    'msg' => $data['MSG'] ?? 'SUCCESS',
                    'bal' => isset($data['BAL']) ? (float) $data['BAL'] : null,
                    'rpid' => $data['RPID'] ?? null,
                    'opid' => $data['OPID'] ?? null,
                    'errorCode' => $data['ERRORCODE'] ?? '200',
                ];
            } elseif ($statusVal === '1') {
                return [
                    'status' => 'pending',
                    'msg' => $data['MSG'] ?? 'PENDING',
                    'bal' => isset($data['BAL']) ? (float) $data['BAL'] : null,
                    'rpid' => $data['RPID'] ?? null,
                    'errorCode' => $data['ERRORCODE'] ?? '200',
                ];
            } else {
                return [
                    'status' => 'failed',
                    'msg' => $data['MSG'] ?? 'Failed',
                    'errorCode' => $data['ERRORCODE'] ?? '500',
                ];
            }

        } catch (\Throwable $e) {
            Log::error('Roundpay Recharge Exception', ['exception' => $e->getMessage()]);

            return [
                'status' => 'failed',
                'msg' => 'Internal Service Error: ' . $e->getMessage(),
                'errorCode' => '500',
            ];
        }
    }
}
